### ISSUE TITLE
Function name background and text color is altered in StatusLine

### ISSUE THREAD

**Issue by jayPare** [mgedmin/chelper.vim#3]
This is what I get:

![image](https://user-images.githubusercontent.com/8458193/27356599-1431ad78-55dd-11e7-8b5a-d27fb1928d40.png)

I'm using Solarized them with dark mode.

**Comment by jayPare** [comment]
It seems to take the hi Normal config. If I change te configuration of Normal, the function name will follow.

**Comment by jayPare** [comment]
My bad, I was using %1 in my StatusLine for unknown reason. Sorry about that.

**Comment by mgedmin** [comment]
No problem!
